build:
  maxIssues: 0

style:
  MagicNumber:
    active: false
  WildcardImport:
    active: false
  ReturnCount:
    active: false
  ThrowsCount:
    active: false
  ForbiddenComment:
    active: false
  MaxLineLength:
    active: false
  UnusedPrivateMember:
    active: true
  UnusedParameter:
    active: false

exceptions:
  TooGenericExceptionCaught:
    active: false

performance:
  active: true
  SpreadOperator:
    active: false

potential-bugs:
  active: true
  ImplicitDefaultLocale:
    active: false

complexity:
  LongMethod:
    active: false
  LongParameterList:
    active: false
  TooManyFunctions:
    active: false
  CyclomaticComplexMethod:
    active: false
  NestedBlockDepth:
    active: false

naming:
  MatchingDeclarationName:
    active: false
  FunctionNaming:
    active: true
    ignoreAnnotated:
      - Composable
      - Test

coroutines:
  active: true
